[env:dfrobot_firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME680 Library@^2.0.5
    adafruit/Adafruit Unified Sensor@^1.1.9
    bblanchon/ArduinoJson@^7.0.4